# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rspec", "~> 3.12", :group => :development
gem "rubocop", "~> 1.42", :group => :development
gem "rubocop-rspec", "~> 2.16", :group => :development

gem "debug", "~> 1.7", :group => :development
